### ISSUE TITLE
ssh-pool v2.0.0

### ISSUE THREAD

**Issue by gregberge** [neoziro/ssh-pool#27]
Hello,

SSH pool is the core of Shipit, the new [Shipit v4](https://github.com/shipitjs/shipit/issues/156) will use ssh-pool v2 under the hood.

The goal of this issue is to list and follow the progression of ssh-pool v2.

I would be happy to have some review from you guys @timkelty, @sgtlambda, @stfoo, @gmaliar.

## Features

- [x] Introduce a "tty" option in "run" method
- [x] Support "cwd" in "run" command https://github.com/shipitjs/shipit/issues/9
- [x] Expose a "isRsyncSupported" method

## Bugs

- [x] Fix parallel issues using scp copy #22
- [ ] Fix command escaping https://github.com/shipitjs/shipit/issues/91 https://github.com/shipitjs/shipit/issues/152

## Deprecation for v3

- [x] Deprecate automatic "sudo" removing when using "asUser"
- [x] Deprecate "copy" method in favor of "copyToRemote", "copyFromRemote",
"scpCopyToRemote" and "scpCopyFromRemote"
- [x] Deprecate using "deploy" as default user
- [x] Deprecate automatic "tty" when detecting "sudo" https://github.com/shipitjs/shipit/issues/56

## Breaking changes

- [x] Drop callbacks support and use native Promises
- [x] Standardise error rejections https://github.com/shipitjs/shipit/issues/154 

## Refactoring & Chores

- [x] Rewrite project in ES2017 targeting Node.js v6+
- [x] Use Jest for testing
- [x] Add Codecov

## Documentation

- [ ] Update readme with new documentation

**Comment by gmaliar** [comment]
@neoziro I can whip up an escaping special values pr quite quick if you'd like but I think that by transitioning from double quotes to single quotes for shell commands we'd have much less problems over time.
Glueing is easier with single quotes and works quite well. I could get that to work as well I think quite quick, let me know which path you'd like me to take and I'll write it up.

Have a look here - http://mywiki.wooledge.org/BashGuide/SpecialCharacters

**Comment by gregberge** [comment]
@gmaliar thank you! The main goal is that user can write commands that actually works. We should start from example and expect a result:

Actually:

```js
run('echo $USER') // "localuser"
run('echo \\$USER') // "remoteuser"
run("echo '$boom'") // ""
run("echo '\\$boom'") // "$boom"
```

I think we should escape "$" and avoid local environment variable replacement because we can do it using `process.env`.


Result should be:

```js
run('echo $USER') // "remoteuser"
run("echo '$boom'") // "$boom"
```

We should also document it.

I don't think the problem comes from single quotes or double quotes, but maybe. The goal is simple if you run a command in your shell, typing it in a "run" command should have the same behaviour.

**Comment by gregberge** [comment]
Moving to a lerna project https://github.com/shipitjs/shipit/issues/156
